[package]
name = "eepxml2rust"
version = "0.1.0"
edition = "2021"

[dependencies]
askama = { version = "0.11" }
buildingblocks = { path = "../../buildingblocks" }
clap = { version = "4.0.0-rc.1", features = ["derive"] }
sxd-document = { version = "0.3" }
sxd-xpath = { version = "0.4" }
