[package]
name = "svd2ghidrac"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "3.2", features = ["derive"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = { version = "1.0" }
sxd-document = { version = "0.3" }
sxd-xpath = { version = "0.4" }
