[package]
name = "winbmptrace"
version = "0.1.0"
edition = "2021"

[dependencies]

[dependencies.windows]
version = "0.43"
features = [
    "Win32_Devices_DeviceAndDriverInstallation",
    "Win32_Devices_Usb",
    "Win32_Foundation",
    "Win32_System_Registry",
]
