[build]
# Arduino Due:
target = "thumbv7m-none-eabi"

[target.'cfg(all(target_arch = "arm", target_os = "none"))']
# link.x is contained in crate cortex-m-rt
rustflags = [
    "-C", "link-arg=-Tlink.x",
]
