[package]
name = "buildingblocks"
version = "0.1.0"
edition = "2021"

[features]
full_esp3_packet = []

[dependencies]
bitflags = { version = "1.3" }
from-to-repr = { version = "0.1.4", features = ["from_to_other"] }
